server:
  port: ${BACKEND_SERVER_PORT}

spring:
  application:
    name: nikke-hub-config-server
  cloud:
    config:
      allow-override: true
      override-none: true
      fail-fast: true

      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          clone-on-start: ${CLONE_ON_START}

  environment:
    system-properties: true
    system-environment: true

eureka:
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}